### ISSUE TITLE
Need a minor change in the firm ware code

### ISSUE THREAD

**Issue by Nithusikan01** [cepdnaclk/e19-3yp-Automated-Hydroponic-System#55]
@e19166 Some Variable in the main.cpp file are naturally boolean type, But they were defined as float data type, If it can be changed to boolean data type It will improve the performance and reduce some unintended conflicts that can happen when transferring the data and handle them in backend application.

Also need to do subscription for receiving some data related to the actions that can be taken when some error related messages are published to the backend by the device. So that the device can take actions to the error handling messages also.

**Comment by e19166** [comment]
Boolean data cause some unexpected errors happened in the hardware configuration as we use C++, arduino platform, Some arduino libraries for esp32 and other framework usages. Your backend can be optimized accordingly more as we use a very common and very simple and very compatible spring framework for that. Study more about that

All the subscriptions are added and tested. Go through the Code again with proper understanding

**Comment by e19166** [comment]
@Nithusikan01 If you are finding it's too difficult to do the backend optimization by yourself, I''ll do that after finishing the whole hardware part for you. Please let me know

**Comment by Nithusikan01** [comment]
Ahh in that case you don't need to worry about that backend is optimized for ALL THE DATA TYPES, and it is fully done, If you don't know how to do that I know the nook and corners of the hardware codes, Let me know if you want me to correct or fix the issues also.

**Comment by e19166** [comment]
@Nithusikan01  Please study about fundamentals and the underlying architecture of esp32, arduino, MQTT and C++ rather than just going through the codes. Then, you will understand the things better.

**Comment by e19166** [comment]
@Nithusikan01 you have mentioned about some unintended conflicts in the first comment send me those conflicts, I'll fix them

Hardware part is fully finished and optimized and tested and demonstrated at the 3rd milestone so no worries about that.

**Comment by e19166** [comment]
@Nithusikan01 no errors in the hardware and the most efficient methods are used in that
You have nothing to correct

**Comment by Nithusikan01** [comment]
Everyone can also think and find out issues .

**Comment by e19166** [comment]
@Nithusikan01 yes, if there is any issue we can

**Comment by e19166** [comment]
@Nithusikan01 Without issues nothing to correct
